# Site settings
title: unamuir
email: 

keywords: webcomic, comic
description: > # this means to ignore newlines until "baseurl:"
 webcomic

baseurl: https://unamuir.com
url: / #Leave this, change the baseurl.

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, image_optim_cache.yml]

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

# Compress our Css
#sass:
#    style: :compressed

permalink: /:categories/:title/

#################################################
####CUSTOM

# Set default header image
header: yes
header_sm: images/cat1.png
header_med: images/cat1.png
header_large: images/cat1.png
header_xl: images/cat1.png

## Thumbnailer taken from https://github.com/chrisanthropic/jekyll-minimagick

# Autogenerate thumbs for comics
mini_magick:

#Create Thumbs for the Archive Page
    thumbnail:
      source: images/comics/
      destination: /images/comics/thumbs
      resize: "182x280^"

#Autogenerate smaller size for small screens       
    small:
      source: images/comics/
      destination: /images/comics/small
      resize: "350x535^"

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image: /images/favicon/favicon-310.png #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image: /images/favicon/favicon-310.png  #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
